services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  db:
    image: postgres:16-alpine
    container_name: arxiv-rag-postgres
    environment:
      - POSTGRES_DB=rag_db
      - POSTGRES_USER=rag_user
      - POSTGRES_PASSWORD=rag_password
      - POSTGRES_HOST_AUTH_METHOD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag_user -d rag_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
  
  vectordb:
    image: qdrant/qdrant:v1.16
    container_name: arxiv-rag-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

  data-ingestion-worker:
    build: ./data_ingestion
    container_name: rag-ingestion-celery-worker
    command: >
      uv run watchfiles --filter python 'uv run celery -A tasks.app worker -l info --concurrency=2'
    env_file:
      - ./data_ingestion/.env
    develop:
      watch:
        - path: ./data_ingestion/src
          action: sync
          target: /app/
          ignore:
              - ./data_ingestion/.venv
              - .venv
        - path: ./data_ingestion/pyproject.toml
          action: rebuild
    depends_on:
      - redis
      - db

  api:
    build: ./arxiv_api
    ports:
      - "8000:8000"
    command: >
      uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./arxiv_api/.env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_BACKEND_URL: redis://redis:6379/1
    develop:
      watch:
        - path: ./arxiv_api/src
          action: sync
          target: /app/
          ignore:
              - ./arxiv_api/.venv
              - .venv
        - path: ./arxiv_api/pyproject.toml
          action: rebuild
    depends_on:
      - redis
      - data-ingestion-worker
  
  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  qdrant_storage:
    driver: local